export const INVALIDATE_POSTS = 'INVALIDATE_POSTS';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_POST = 'RECEIVE_POST';
export const EDIT_POST = 'EDIT_POSTS';
export const DELETE_POST = 'DELETE_POSTS';
export const VOTE_POST = 'VOTE_POSTS';
export const ADD_POST = 'ADD_POST';
export const GET_POSTS_BY_CATEGORIES = 'GET_POSTS_BY_CATEGORIES';

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';

export const SELECT_SORT = 'SELECT_SORT';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const INVALIDATE_CATEGORIES = 'INVALIDATE_CATEGORIES';